// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/14/2024, 6:10:45 AM
const configMerger = require("/Users/ikechukwuokafor/Downloads/CareCove/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/ikechukwuokafor/Downloads/CareCove/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/plugins/**/*.{js,ts,mjs}","/Users/ikechukwuokafor/Downloads/CareCove/composables/**/*.{js,ts,mjs}","/Users/ikechukwuokafor/Downloads/CareCove/utils/**/*.{js,ts,mjs}","/Users/ikechukwuokafor/Downloads/CareCove/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ikechukwuokafor/Downloads/CareCove/app.config.{js,ts,mjs}"] }));

module.exports = config
